services:
  - type: web
    name: newbie-recp-discord-bot-diag # 診断用なので名前を少し変えます
    env: python
    plan: free

    # Pythonのバージョンを指定
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - fromGroup: newbie-bot-secrets # 環境グループをリンク

    # ★★★ 起動コマンドを診断用に変更 ★★★
    # Linuxの `printenv` コマンドで、存在する全ての環境変数を表示します
    startCommand: "printenv"
