services:
  - type: web
    name: newbie-recp-discord-bot
    env: python
    plan: free

    # ビルドと起動の設定
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    
    # 環境変数 - Pythonのバージョンのみを指定します
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
