services:
  - type: web
    name: newbie-recp-discord-bot  # あなたのサービス名（自由に変更可）
    env: python
    plan: free # 無料プランを指定
    
    # Pythonのバージョンをここで強制的に指定
    pythonVersion: "3.12" 

    # ビルドコマンド
    buildCommand: "pip install -r requirements.txt"
    
    # 起動コマンド
    startCommand: "python main.py"

    # 環境変数グループ（後でダッシュボードから設定）
    # ここに直接キーと値を書くのではなく、RenderのUIから設定します
    envVarGroups:
      - name: discord-bot-secrets
