services:
  - type: web
    name: newbie-recp-discord-bot
    env: python
    plan: free

    # ビルドと起動の設定
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    
    # 環境変数 - ここに直接書き込みます
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: DISCORD_TOKEN
        sync: false # この値をUIから変更しても、yamlで上書きしないようにする設定
      - key: MONGO_URI
        sync: false # 同上
